class Level {
    backgroundColor = "#fff";
    ballSrc = "";
    paddleSrc = "";
    bricks = new Map();
}

const cosmos = new Level();
cosmos.backgroundColor = "#000";
cosmos.ballSrc = "img/cosmos/ball.bmp";
cosmos.paddleSrc = "img/cosmos/paddle.bmp";
cosmos.bricks.set("0,3", "yellowBrick");
cosmos.bricks.set("0,4", "grayBrick");
cosmos.bricks.set("0,5", "grayBrick");
cosmos.bricks.set("0,6", "grayBrick");
cosmos.bricks.set("0,7", "grayBrick");
cosmos.bricks.set("1,2", "orangeBrick");
cosmos.bricks.set("1,3", "yellowBrick");
cosmos.bricks.set("1,4", "lightGrayBrick");
cosmos.bricks.set("1,5", "lightGrayBrick");
cosmos.bricks.set("1,6", "lightGrayBrick");
cosmos.bricks.set("1,7", "lightGrayBrick");
cosmos.bricks.set("1,8", "grayBrick");
cosmos.bricks.set("2,1", "redBrick");
cosmos.bricks.set("2,2", "orangeBrick");
cosmos.bricks.set("2,3", "yellowBrick");
cosmos.bricks.set("2,4", "lightGrayBrick");
cosmos.bricks.set("2,5", "lightGrayBrick");
cosmos.bricks.set("2,6", "lightGrayBrick");
cosmos.bricks.set("2,7", "lightGrayBrick");
cosmos.bricks.set("2,8", "lightGrayBrick");
cosmos.bricks.set("2,9", "grayBrick");
cosmos.bricks.set("3,0", "redBrick");
cosmos.bricks.set("3,1", "redBrick");
cosmos.bricks.set("3,2", "orangeBrick");
cosmos.bricks.set("3,3", "yellowBrick");
cosmos.bricks.set("3,4", "lightGrayBrick");
cosmos.bricks.set("3,5", "blueBrick");
cosmos.bricks.set("3,6", "lightGrayBrick");
cosmos.bricks.set("3,7", "lightGrayBrick");
cosmos.bricks.set("3,8", "lightGrayBrick");
cosmos.bricks.set("3,9", "lightGrayBrick");
cosmos.bricks.set("3,10", "grayBrick");
cosmos.bricks.set("4,1", "redBrick");
cosmos.bricks.set("4,2", "orangeBrick");
cosmos.bricks.set("4,3", "yellowBrick");
cosmos.bricks.set("4,4", "lightGrayBrick");
cosmos.bricks.set("4,5", "lightGrayBrick");
cosmos.bricks.set("4,6", "lightGrayBrick");
cosmos.bricks.set("4,7", "lightGrayBrick");
cosmos.bricks.set("4,8", "lightGrayBrick");
cosmos.bricks.set("4,9", "grayBrick");
cosmos.bricks.set("5,2", "orangeBrick");
cosmos.bricks.set("5,3", "yellowBrick");
cosmos.bricks.set("5,4", "lightGrayBrick");
cosmos.bricks.set("5,5", "lightGrayBrick");
cosmos.bricks.set("5,6", "lightGrayBrick");
cosmos.bricks.set("5,7", "lightGrayBrick");
cosmos.bricks.set("5,8", "grayBrick");
cosmos.bricks.set("6,3", "yellowBrick");
cosmos.bricks.set("6,4", "grayBrick");
cosmos.bricks.set("6,5", "grayBrick");
cosmos.bricks.set("6,6", "grayBrick");
cosmos.bricks.set("6,7", "grayBrick");

const formula = new Level();
formula.backgroundColor = "#7f7f7f";
formula.ballSrc = "img/formula/ball.bmp";
formula.paddleSrc = "img/formula/paddle.bmp";
formula.bricks.set("0,1", "blackBrick");
formula.bricks.set("0,3", "redBrick");
formula.bricks.set("0,4", "redBrick");
formula.bricks.set("0,7", "blackBrick");
formula.bricks.set("1,1", "redBrick");
formula.bricks.set("1,2", "redBrick");
formula.bricks.set("1,3", "redBrick");
formula.bricks.set("1,4", "redBrick");
formula.bricks.set("1,5", "redBrick");
formula.bricks.set("1,7", "redBrick");
formula.bricks.set("1,9", "redBrick");
formula.bricks.set("2,1", "redBrick");
formula.bricks.set("2,2", "redBrick");
formula.bricks.set("2,3", "redBrick");
formula.bricks.set("2,4", "redBrick");
formula.bricks.set("2,5", "lightGrayBrick");
formula.bricks.set("2,6", "redBrick");
formula.bricks.set("2,7", "redBrick");
formula.bricks.set("2,8", "redBrick");
formula.bricks.set("2,9", "redBrick");
formula.bricks.set("3,1", "redBrick");
formula.bricks.set("3,2", "redBrick");
formula.bricks.set("3,3", "redBrick");
formula.bricks.set("3,4", "redBrick");
formula.bricks.set("3,5", "lightGrayBrick");
formula.bricks.set("3,6", "redBrick");
formula.bricks.set("3,7", "redBrick");
formula.bricks.set("3,8", "redBrick");
formula.bricks.set("3,9", "redBrick");
formula.bricks.set("4,1", "redBrick");
formula.bricks.set("4,2", "redBrick");
formula.bricks.set("4,3", "redBrick");
formula.bricks.set("4,4", "redBrick");
formula.bricks.set("4,5", "redBrick");
formula.bricks.set("4,7", "redBrick");
formula.bricks.set("4,9", "redBrick");
formula.bricks.set("5,1", "blackBrick");
formula.bricks.set("5,3", "redBrick");
formula.bricks.set("5,4", "redBrick");
formula.bricks.set("5,7", "blackBrick");

const castle = new Level();
castle.backgroundColor = "#3f48cc";
castle.ballSrc = "img/castle/ball.bmp";
castle.paddleSrc = "img/castle/paddle.bmp";
castle.bricks.set("0,1", "brick");
castle.bricks.set("0,3", "brick");
castle.bricks.set("0,5", "brick");
castle.bricks.set("0,7", "brick");
castle.bricks.set("0,9", "brick");
castle.bricks.set("1,1", "brick");
castle.bricks.set("1,2", "brick");
castle.bricks.set("1,3", "brick");
castle.bricks.set("1,4", "brick");
castle.bricks.set("1,5", "brick");
castle.bricks.set("1,6", "brick");
castle.bricks.set("1,7", "brick");
castle.bricks.set("1,8", "brick");
castle.bricks.set("1,9", "brick");
castle.bricks.set("2,1", "brick");
castle.bricks.set("2,2", "blueBrick");
castle.bricks.set("2,3", "brick");
castle.bricks.set("2,4", "brick");
castle.bricks.set("2,5", "lightGrayBrick");
castle.bricks.set("2,6", "brick");
castle.bricks.set("2,7", "brick");
castle.bricks.set("2,8", "blueBrick");
castle.bricks.set("2,9", "brick");
castle.bricks.set("3,1", "brick");
castle.bricks.set("3,2", "blueBrick");
castle.bricks.set("3,3", "brick");
castle.bricks.set("3,4", "lightGrayBrick");
castle.bricks.set("3,5", "lightGrayBrick");
castle.bricks.set("3,6", "lightGrayBrick");
castle.bricks.set("3,7", "brick");
castle.bricks.set("3,8", "blueBrick");
castle.bricks.set("3,9", "brick");
castle.bricks.set("4,1", "brick");
castle.bricks.set("4,2", "blueBrick");
castle.bricks.set("4,3", "brick");
castle.bricks.set("4,4", "lightGrayBrick");
castle.bricks.set("4,5", "blackBrick");
castle.bricks.set("4,6", "lightGrayBrick");
castle.bricks.set("4,7", "brick");
castle.bricks.set("4,8", "blueBrick");
castle.bricks.set("4,9", "brick");
castle.bricks.set("5,1", "brick");
castle.bricks.set("5,2", "blueBrick");
castle.bricks.set("5,3", "brick");
castle.bricks.set("5,4", "lightGrayBrick");
castle.bricks.set("5,5", "blackBrick");
castle.bricks.set("5,6", "lightGrayBrick");
castle.bricks.set("5,7", "brick");
castle.bricks.set("5,8", "blueBrick");
castle.bricks.set("5,9", "brick");
castle.bricks.set("6,1", "brick");
castle.bricks.set("6,2", "brick");
castle.bricks.set("6,3", "brick");
castle.bricks.set("6,4", "lightGrayBrick");
castle.bricks.set("6,5", "blackBrick");
castle.bricks.set("6,6", "lightGrayBrick");
castle.bricks.set("6,7", "brick");
castle.bricks.set("6,8", "brick");
castle.bricks.set("6,9", "brick");

const chess = new Level();
chess.backgroundColor = "#188546";
chess.ballSrc = "img/chess/ball.bmp";
chess.paddleSrc = "img/chess/paddle.bmp";
chess.bricks.set("0,1", "beigeBrick");
chess.bricks.set("0,2", "brownBrick");
chess.bricks.set("0,3", "beigeBrick");
chess.bricks.set("0,4", "brownBrick");
chess.bricks.set("0,5", "beigeBrick");
chess.bricks.set("0,6", "brownBrick");
chess.bricks.set("0,7", "beigeBrick");
chess.bricks.set("0,8", "brownBrick");
chess.bricks.set("0,9", "beigeBrick");
chess.bricks.set("1,1", "brownBrick");
chess.bricks.set("1,2", "beigeBrick");
chess.bricks.set("1,3", "brownBrick");
chess.bricks.set("1,4", "beigeBrick");
chess.bricks.set("1,5", "brownBrick");
chess.bricks.set("1,6", "beigeBrick");
chess.bricks.set("1,7", "brownBrick");
chess.bricks.set("1,8", "beigeBrick");
chess.bricks.set("1,9", "brownBrick");
chess.bricks.set("2,1", "beigeBrick");
chess.bricks.set("2,2", "brownBrick");
chess.bricks.set("2,3", "beigeBrick");
chess.bricks.set("2,4", "brownBrick");
chess.bricks.set("2,5", "beigeBrick");
chess.bricks.set("2,6", "brownBrick");
chess.bricks.set("2,7", "beigeBrick");
chess.bricks.set("2,8", "brownBrick");
chess.bricks.set("2,9", "beigeBrick");
chess.bricks.set("3,1", "brownBrick");
chess.bricks.set("3,2", "beigeBrick");
chess.bricks.set("3,3", "brownBrick");
chess.bricks.set("3,4", "beigeBrick");
chess.bricks.set("3,5", "brownBrick");
chess.bricks.set("3,6", "beigeBrick");
chess.bricks.set("3,7", "brownBrick");
chess.bricks.set("3,8", "beigeBrick");
chess.bricks.set("3,9", "brownBrick");
chess.bricks.set("4,1", "beigeBrick");
chess.bricks.set("4,2", "brownBrick");
chess.bricks.set("4,3", "beigeBrick");
chess.bricks.set("4,4", "brownBrick");
chess.bricks.set("4,5", "beigeBrick");
chess.bricks.set("4,6", "brownBrick");
chess.bricks.set("4,7", "beigeBrick");
chess.bricks.set("4,8", "brownBrick");
chess.bricks.set("4,9", "beigeBrick");
chess.bricks.set("5,1", "brownBrick");
chess.bricks.set("5,2", "beigeBrick");
chess.bricks.set("5,3", "brownBrick");
chess.bricks.set("5,4", "beigeBrick");
chess.bricks.set("5,5", "brownBrick");
chess.bricks.set("5,6", "beigeBrick");
chess.bricks.set("5,7", "brownBrick");
chess.bricks.set("5,8", "beigeBrick");
chess.bricks.set("5,9", "brownBrick");
chess.bricks.set("6,1", "beigeBrick");
chess.bricks.set("6,2", "brownBrick");
chess.bricks.set("6,3", "beigeBrick");
chess.bricks.set("6,4", "brownBrick");
chess.bricks.set("6,5", "beigeBrick");
chess.bricks.set("6,6", "brownBrick");
chess.bricks.set("6,7", "beigeBrick");
chess.bricks.set("6,8", "brownBrick");
chess.bricks.set("6,9", "beigeBrick");
chess.bricks.set("7,1", "brownBrick");
chess.bricks.set("7,2", "beigeBrick");
chess.bricks.set("7,3", "brownBrick");
chess.bricks.set("7,4", "beigeBrick");
chess.bricks.set("7,5", "brownBrick");
chess.bricks.set("7,6", "beigeBrick");
chess.bricks.set("7,7", "brownBrick");
chess.bricks.set("7,8", "beigeBrick");
chess.bricks.set("7,9", "brownBrick");

const fish = new Level();
fish.backgroundColor = "#35d0fd";
fish.ballSrc = "img/fish/ball.bmp";
fish.paddleSrc = "img/fish/paddle.bmp";
fish.bricks.set("0,5", "yellowBrick");
fish.bricks.set("1,5", "yellowBrick");
fish.bricks.set("1,6", "yellowBrick");
fish.bricks.set("2,0", "yellowBrick");
fish.bricks.set("2,1", "yellowBrick");
fish.bricks.set("2,3", "orangeBrick");
fish.bricks.set("2,4", "orangeBrick");
fish.bricks.set("2,5", "orangeBrick");
fish.bricks.set("2,6", "orangeBrick");
fish.bricks.set("2,7", "orangeBrick");
fish.bricks.set("3,1", "yellowBrick");
fish.bricks.set("3,2", "yellowBrick");
fish.bricks.set("3,3", "orangeBrick");
fish.bricks.set("3,4", "yellowBrick");
fish.bricks.set("3,5", "orangeBrick");
fish.bricks.set("3,6", "yellowBrick");
fish.bricks.set("3,7", "orangeBrick");
fish.bricks.set("3,8", "orangeBrick");
fish.bricks.set("3,9", "orangeBrick");
fish.bricks.set("4,2", "yellowBrick");
fish.bricks.set("4,3", "orangeBrick");
fish.bricks.set("4,4", "yellowBrick");
fish.bricks.set("4,5", "orangeBrick");
fish.bricks.set("4,6", "yellowBrick");
fish.bricks.set("4,7", "orangeBrick");
fish.bricks.set("4,8", "blackBrick");
fish.bricks.set("4,9", "orangeBrick");
fish.bricks.set("4,10", "orangeBrick");
fish.bricks.set("5,1", "yellowBrick");
fish.bricks.set("5,2", "yellowBrick");
fish.bricks.set("5,3", "orangeBrick");
fish.bricks.set("5,4", "yellowBrick");
fish.bricks.set("5,5", "orangeBrick");
fish.bricks.set("5,6", "yellowBrick");
fish.bricks.set("5,7", "orangeBrick");
fish.bricks.set("5,8", "orangeBrick");
fish.bricks.set("5,9", "orangeBrick");
fish.bricks.set("6,0", "yellowBrick");
fish.bricks.set("6,1", "yellowBrick");
fish.bricks.set("6,3", "orangeBrick");
fish.bricks.set("6,4", "orangeBrick");
fish.bricks.set("6,5", "orangeBrick");
fish.bricks.set("6,6", "orangeBrick");
fish.bricks.set("6,7", "orangeBrick");
fish.bricks.set("7,5", "yellowBrick");
fish.bricks.set("7,6", "yellowBrick");
fish.bricks.set("8,5", "yellowBrick");

const duck = new Level();
duck.backgroundColor = "#a349a4";
duck.ballSrc = "img/duck/ball.bmp";
duck.paddleSrc = "img/duck/paddle.bmp";
duck.bricks.set("0,0", "blueBrick");
duck.bricks.set("0,1", "blueBrick");
duck.bricks.set("0,2", "blueBrick");
duck.bricks.set("0,3", "blueBrick");
duck.bricks.set("0,4", "blueBrick");
duck.bricks.set("0,5", "blueBrick");
duck.bricks.set("0,6", "greenBrick");
duck.bricks.set("0,7", "greenBrick");
duck.bricks.set("0,8", "greenBrick");
duck.bricks.set("0,9", "blueBrick");
duck.bricks.set("0,10", "blueBrick");
duck.bricks.set("1,0", "blueBrick");
duck.bricks.set("1,1", "blueBrick");
duck.bricks.set("1,2", "blueBrick");
duck.bricks.set("1,3", "blueBrick");
duck.bricks.set("1,4", "blueBrick");
duck.bricks.set("1,5", "blueBrick");
duck.bricks.set("1,6", "greenBrick");
duck.bricks.set("1,7", "blackBrick");
duck.bricks.set("1,8", "greenBrick");
duck.bricks.set("1,9", "yellowBrick");
duck.bricks.set("1,10", "blueBrick");
duck.bricks.set("2,0", "blueBrick");
duck.bricks.set("2,1", "blueBrick");
duck.bricks.set("2,2", "blueBrick");
duck.bricks.set("2,3", "blueBrick");
duck.bricks.set("2,4", "blueBrick");
duck.bricks.set("2,5", "blueBrick");
duck.bricks.set("2,6", "greenBrick");
duck.bricks.set("2,7", "greenBrick");
duck.bricks.set("2,8", "greenBrick");
duck.bricks.set("2,9", "yellowBrick");
duck.bricks.set("2,10", "yellowBrick");
duck.bricks.set("3,0", "blueBrick");
duck.bricks.set("3,1", "blueBrick");
duck.bricks.set("3,2", "lightGrayBrick");
duck.bricks.set("3,3", "lightGrayBrick");
duck.bricks.set("3,4", "lightGrayBrick");
duck.bricks.set("3,5", "lightGrayBrick");
duck.bricks.set("3,6", "greenBrick");
duck.bricks.set("3,7", "greenBrick");
duck.bricks.set("3,8", "greenBrick");
duck.bricks.set("3,9", "yellowBrick");
duck.bricks.set("3,10", "yellowBrick");
duck.bricks.set("4,0", "blueBrick");
duck.bricks.set("4,1", "lightGrayBrick");
duck.bricks.set("4,2", "lightGrayBrick");
duck.bricks.set("4,3", "grayBrick");
duck.bricks.set("4,4", "grayBrick");
duck.bricks.set("4,5", "grayBrick");
duck.bricks.set("4,6", "lightGrayBrick");
duck.bricks.set("4,7", "lightGrayBrick");
duck.bricks.set("4,8", "blueBrick");
duck.bricks.set("4,9", "blueBrick");
duck.bricks.set("4,10", "blueBrick");
duck.bricks.set("5,0", "lightGrayBrick");
duck.bricks.set("5,1", "lightGrayBrick");
duck.bricks.set("5,2", "grayBrick");
duck.bricks.set("5,3", "lightGrayBrick");
duck.bricks.set("5,4", "lightGrayBrick");
duck.bricks.set("5,5", "lightGrayBrick");
duck.bricks.set("5,6", "lightGrayBrick");
duck.bricks.set("5,7", "lightGrayBrick");
duck.bricks.set("5,8", "lightGrayBrick");
duck.bricks.set("5,9", "blueBrick");
duck.bricks.set("5,10", "blueBrick");
duck.bricks.set("6,0", "blueBrick");
duck.bricks.set("6,1", "lightGrayBrick");
duck.bricks.set("6,2", "lightGrayBrick");
duck.bricks.set("6,3", "grayBrick");
duck.bricks.set("6,4", "grayBrick");
duck.bricks.set("6,5", "grayBrick");
duck.bricks.set("6,6", "lightGrayBrick");
duck.bricks.set("6,7", "lightGrayBrick");
duck.bricks.set("6,8", "blueBrick");
duck.bricks.set("6,9", "blueBrick");
duck.bricks.set("6,10", "blueBrick");
duck.bricks.set("7,0", "blueBrick");
duck.bricks.set("7,1", "blueBrick");
duck.bricks.set("7,2", "lightGrayBrick");
duck.bricks.set("7,3", "lightGrayBrick");
duck.bricks.set("7,4", "lightGrayBrick");
duck.bricks.set("7,5", "lightGrayBrick");
duck.bricks.set("7,6", "lightGrayBrick");
duck.bricks.set("7,7", "lightGrayBrick");
duck.bricks.set("7,8", "blueBrick");
duck.bricks.set("7,9", "blueBrick");
duck.bricks.set("7,10", "blueBrick");
duck.bricks.set("8,0", "blueBrick");
duck.bricks.set("8,1", "blueBrick");
duck.bricks.set("8,2", "blueBrick");
duck.bricks.set("8,3", "blueBrick");
duck.bricks.set("8,4", "blueBrick");
duck.bricks.set("8,5", "blueBrick");
duck.bricks.set("8,6", "blueBrick");
duck.bricks.set("8,7", "blueBrick");
duck.bricks.set("8,8", "blueBrick");
duck.bricks.set("8,9", "blueBrick");
duck.bricks.set("8,10", "blueBrick");

export const levels = {
    cosmos,
    formula,
    castle,
    chess,
    fish,
    duck
}